
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "title": "Laptop Acer Aspire",
    "description": "Acer Aspire 5 Slim Laptop, 15.6 inches Full HD, AMD Ryzen 3 3200U, Vega 3 Graphics, 4GB DDR4, 128GB SSD, Windows 10 in S Mode, A515-43-R19L, Silver",
    "code": "A515-43-R19L",
    "price": 349.99,
    "stock": 25,
    "category": "Electronics"
}
###


POST http://localhost:8080/api/products
Content-Type: application/json 

{
    "title": "Apple MacBook Pro",
    "description": "Apple MacBook Pro (16-inch, 16GB RAM, 512GB Storage, 2.6GHz Intel Core i7) - Space Gray",
    "code": "MBP16-512GB-SG",
    "price": 2399.00,
    "stock": 15,
    "category": "Laptops"
}

###
PUT http://localhost:8080/api/products/66b4f42ccb443a3228e6a860
Content-Type: application/json 

{
    "thumbnails": [
        "/images/products/acer_aspire.webp"
    ]
}

###
GET http://localhost:8080/api/products/66b4f42ccb443a3228e6a860



###
DELETE http://localhost:8080/api/products/66b4f42ccb443a3228e6a865

###
POST http://localhost:8080/api/carts
Content-Type: application/json

{
    "products": [
        {
            "product": "66e988ce312e0c20b2edd6d0",
            "quantity": 2
        },
        {
            "product": "66e988ce312e0c20b2edd6d2",
            "quantity": 3
        }
    ]
}

###
POST http://localhost:8080/api/carts/66b52ed63543c41726107998/product/66b4f42ccb443a3228e6a860
Content-Type: application/json

{
    "quantity": 1
}

###

POST http://localhost:8080/api/carts/66b52ed63543c41726107998/product/66b4f42ccb443a3228e6a86e
Content-Type: application/json

{
    "quantity": 2
}



###
DELETE http://localhost:8080/api/carts/66b52ed63543c41726107998/product/66b4f42ccb443a3228e6a861


### 
PUT http://localhost:8080/api/carts/66b52ed63543c41726107998 
Content-Type: application/json

{
    "products": [
        {
            "product": "66b4f42ccb443a3228e6a872",
            "quantity": 3
        }, 
        {
            "product": "66b4f42ccb443a3228e6a874",
            "quantity": 1
        },
        {
            "product": "66b4f42ccb443a3228e6a878",
            "quantity": 2
        }
    ]
}

###
PUT http://localhost:8080/api/carts/66b52ed63543c41726107998/product/66b4f42ccb443a3228e6a878
Content-Type: application/json

{
    "quantity": 5
}

###
DELETE http://localhost:8080/api/carts/66b52ed63543c41726107998

